### ISSUE TITLE
Is perch math off?

### ISSUE THREAD

**Issue by iros** [bocoup/bots#53]
![image](https://cloud.githubusercontent.com/assets/18690/13023053/1bef284c-d1b3-11e5-87b5-e83ceb7dd395.png)

If our average is <4 than we can't be over the plan if the plan was 4. Is something off here?

**Comment by tkellen** [comment]
Sorry for the slow reply here @iros! This is not off. Here's the numbers in the formula for your review:

billable employees: **18**
minimum planned perch weeks per employee: **4**
planned perch weeks for whole company: **72**
percentage into year: **14.5%**
target usage at this point of the year = **10.45 weeks** (planned perch weeks for whole company * percentage into year)
verified perch weeks year to date: **33.80 weeks**
differential against target: **23.35** (over)

... and the status as of today:
Perch Status as of February 22nd, 2016
> You have used ​*0.00*​ of ​*4.00*​ planned perch weeks this year.
> The company average for billable team members is ​*1.21*​ verified perch weeks this year.
> We are ​*over*​ our company-wide planned perch by ​*23.35*​ verified perch weeks this year.
> ​*4*​ out of ​*18*​ billable team members have had 4+ verified perch weeks this year.
> You ​*are not*​ currently coded as a billable team member. Please email hr@bocoup.com if this needs to be updated.

If you see any holes in this math, please let me know. Otherwise, can you close this?

**Comment by iros** [comment]
I see what you mean now. This is according to your projection of _where we are in time_. I'm wondering if there's any language we could add to clarify that? Maybe something like:

"We planned to have XX weeks of perch by this time. We have delivered YY weeks, which is over by YY-XX weeks."

**Comment by tkellen** [comment]
I think that makes sense. I'd land a PR for this, otherwise this is likely going to sit on the back burner for awhile.

**Comment by iros** [comment]
It's not likely I'll have bandwidth for a few weeks. Can we leave this open
and I'll try to do so?

Irene Ros
Director of Data Visualization, Bocoup, http://bocoup.com/datavis
Organizer and Program Chair, OpenVis Conf, http://openvisconf.com
irene@bocoup.com

**Comment by tkellen** [comment]
:+1:
